### ISSUE TITLE
[BUG] Error opening TethysDash in tethys 4.3.8.post3.dev3

### ISSUE THREAD

**Issue by Sonia-96** [tethysplatform/tethys#1187]
**Describe the bug**
I have [tethysdash](https://github.com/tethysplatform/tethysapp-tethys_dash) installed in the latest tethys environment. When I tried to open the app TethysDash, I got an error: `AttributeError: type object 'App' has no attribute 'path'`. 

Other information: 
- I also tested another tethysapp like tribs with the latest tethys, but it works fine.
- I rolled back tethys before the commit [Quotas bug fix (#1158)](https://github.com/tethysplatform/tethys/commit/a5faefb1c095925e48243e609ae34f265991555d), and the error is gone

**To Reproduce**
1. Pull the latest changes of tethys
2. enter tethys folder and run `pip install -e.`
3. run `tethys manage start`
4. Go to the page `http://127.0.0.1:8000/apps/` and click the TethysDash app

**Expected behavior**
The app should open normally.

**Errors/Traceback**
ERROR:django.request:Internal Server Error: /apps/tethysdash/dashboards/
Traceback (most recent call last):
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
        request, *callback_args, **callback_kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/tethys/miniconda3/envs/tethys/lib/python3.13/site-packages/asgiref/sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
  File "/home/tethys/tethysdev/tethysapp-tethys_dash/tethysapp/tethysdash/controllers.py", line 124, in dashboards
    dashboards = get_dashboards(user)
  File "/home/tethys/tethysdev/tethysapp-tethys_dash/tethysapp/tethysdash/model.py", line 461, in get_dashboards
    dashboard_dict["user"] = parse_db_dashboard(user_dashboards, dashboard_view)
                             ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tethys/tethysdev/tethysapp-tethys_dash/tethysapp/tethysdash/model.py", line 406, in parse_db_dashboard
    app_media = get_app_media(App)
  File "/home/tethys/tethys/tethys_apps/base/paths.py", line 477, in get_app_media
    return _get_app_media(app_or_request)
  File "/home/tethys/tethys/tethys_apps/base/paths.py", line 458, in _get_app_media
    _check_app_quota(app_or_request)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/tethys/tethys/tethys_apps/base/paths.py", line 272, in _check_app_quota
    app_model = get_active_app(app_or_request, get_class=False)
  File "/home/tethys/tethys/tethys_apps/utilities.py", line 139, in get_active_app
    the_url = request.path
              ^^^^^^^^^^^^
AttributeError: type object 'App' has no attribute 'path'


**Tethys Environment Information**
Include output from these commands:
- tethys version: 4.3.8.post3.dev3

**Additional context**
 It used to work with tethys-4.3.8.
